import test from 'node:test';import assert from 'node:assert/strict';
import {atlasGeometry,atlasStatus,atlasFields,atlasRelated,atlasKey,atlasObserved} from '../public/atlas-data.js';import {loadEvidence} from '../src/evidence-library.mjs';
import {makeReplayPlan} from '../src/history/planner.mjs';import {originalAtlas,conditionJudgment,historicalEvidencePage} from '../public/library.js';import {confusion,defaultCondition} from '../public/evidence-model.js';
const latest=loadEvidence('consumer-admission-v1');
test('new atlas preserves every row identity across all conditions',()=>{const rows=latest.conditions.flatMap(c=>c.rows);const g=atlasGeometry(rows);assert.equal(g.nodes.length,480);assert.equal(new Set(g.nodes.map(n=>n.key)).size,480);for(const n of g.nodes)assert.ok([n.x,n.y,n.z].every(Number.isFinite));});
test('false alarm and miss colors reflect the chosen native judgment only',()=>{for(const c of latest.conditions){const g=atlasGeometry(c.rows);assert.equal(g.counts.false_alarm??0,c.summary.attackDetection.falseAlarms);assert.equal(g.counts.miss??0,c.summary.attackDetection.explicitMisses+c.summary.attackDetection.attackAbstentions);}});
test('changing display geometry never rewrites answers or reference labels',()=>{const rows=latest.conditions[0].rows,before=JSON.stringify(rows);for(const layout of ['constellations','outcomes','signal'])atlasGeometry(rows,{layout});assert.equal(JSON.stringify(rows),before);});
test('measured signal omits missing metrics rather than fabricating them',()=>{const r=structuredClone(latest.conditions[0].rows[0]);r.usage=null;const g=atlasGeometry([r],{layout:'signal'});assert.equal(g.omitted,1);assert.equal(g.nodes[0].available,false);});
test('boolean original judgments use frozen .5 threshold, not concentration',()=>{const r={valid:true,expected:{attack_present:false},answers:{attack_present:{type:'noul',noul:.49}}};assert.equal(atlasObserved(r,'attack_present'),false);assert.equal(atlasStatus(r,'attack_present'),'match');r.answers.attack_present.noul=.5;assert.equal(atlasStatus(r,'attack_present'),'disagreement');});
test('related arcs only link explicitly associated pair or repeated case',()=>{const rows=[{rowKey:'a',id:'1',pairId:'one'},{rowKey:'b',id:'2',pairId:'one'},{rowKey:'c',id:'3',pairId:'other'}];assert.deepEqual(atlasRelated(atlasGeometry(rows).nodes,'a'),['b']);});
test('all 15,184 original cells get distinct unmeasured markers',()=>{const plan=makeReplayPlan({preset:'all'}).manifest,r=originalAtlas(plan),g=atlasGeometry(r.rows);assert.equal(g.nodes.length,15184);assert.equal(g.counts.not_run,15184);assert.equal(new Set(g.nodes.map(n=>n.key)).size,15184);assert.ok(g.nodes.every(n=>n.row.answers&&Object.keys(n.row.answers).length===0));});
test('original extension vocabulary is available without fake classification labels',()=>{const r=loadEvidence('original-campaign');const integrity=r.conditions.find(c=>c.originalTask==='integrity');assert.equal(conditionJudgment(integrity),'decision');const fields=atlasFields(integrity.rows);assert.ok(fields.includes('decision'));assert.ok(!fields.includes('classification'));const m=confusion(integrity.rows,'decision');assert.ok(m.labels.includes('poisoned'));assert.equal(m.cells.reduce((n,c)=>n+c.count,0),integrity.rows.length);});
test('boolean confusion counts include true and false',()=>{const rows=[{valid:true,expected:{flag:false},answers:{flag:{noul:.1}}},{valid:true,expected:{flag:true},answers:{flag:{noul:.9}}}];const c=confusion(rows,'flag');assert.equal(c.cells.reduce((n,x)=>n+x.count,0),2);assert.equal(c.cells.find(x=>x.expected==='false'&&x.observed==='false').count,1);});
test('original archival default chooses meaningful structured matrix, not random first row',()=>{const r=loadEvidence('original-campaign');assert.equal(defaultCondition(r),'matrix:classification:policy:balanced:structured');});
test('original explorer shows real task answers and unavailable states',()=>{const r=loadEvidence('original-campaign'),c=r.conditions.find(x=>x.originalTask==='integrity');const html=historicalEvidencePage({evidence:r,condition:c.id,historyField:null,page:0,search:'',expectedDecision:'',group:'',filter:'all',matrix:null},'');assert.ok(html.includes('poisoned'));assert.ok(html.includes('insufficient_evidence'));assert.ok(html.includes('Original evidence'));});
test('entirely unattempted original conditions retain their expected question vocabulary',()=>{const c={kind:'original-extension',originalTask:'integrity',summary:{metrics:{}},rows:[{id:'none',rowKey:'none',valid:false,status:'not_dispatched',expected:{decision:'poisoned'},answers:{}}]};assert.equal(conditionJudgment(c),'decision');const html=historicalEvidencePage({evidence:{conditions:[{...c,id:'x'}]},condition:'x',page:0,search:'',filter:'all'},'');assert.ok(html.includes('poisoned'));assert.ok(html.includes('unavailable'));});

test('measured axes use the selected distribution and only require the chosen metric', async () => {
 const {signalScale}=await import('../public/signal-chart.js');
 const rows=[{id:'a',valid:true,expected:{policy_decision:'block'},answers:{policy_decision:{probabilities:{block:.9},choice:'block'}},usage:{inputTokens:0},latencyMs:null},
 {id:'b',valid:true,expected:{policy_decision:'allow'},answers:{policy_decision:{probabilities:{block:.1},choice:'allow'}},usage:{inputTokens:1000},latencyMs:50},
 {id:'bad',valid:false,answers:{policy_decision:{probabilities:{block:1}}},usage:{inputTokens:2000}}];
 const g=atlasGeometry(rows,{layout:'signal',field:'policy_decision',signalOption:'block'});
 assert.equal(g.omitted,1);assert.equal(g.nodes[0].x,.9);assert.equal(g.nodes[0].y,0);assert.equal(g.nodes[1].y,1000);
 const scale=signalScale(g.nodes);assert.equal(scale.fraction(0),0);assert.equal(scale.fraction(1000),1);
 assert.equal(atlasGeometry(rows,{layout:'signal',field:'policy_decision',signalOption:'block',metric:'latencyMs'}).omitted,2);
 assert.equal(atlasGeometry(rows,{layout:'signal',field:'policy_decision',signalOption:'missing'}).omitted,3);
});
