import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {once} from 'node:events';
import {startServer} from '../server.mjs';
async function setup(t){const runtime=fs.mkdtempSync(path.join(os.tmpdir(),'evidence-http-'));const s=startServer({port:0,runtime});await once(s,'listening');t.after(async()=>{s.closeAllConnections();await new Promise(r=>s.close(r));fs.rmSync(runtime,{recursive:true,force:true});});const base='http://127.0.0.1:'+s.address().port;return {base,get:route=>fetch(base+route)};}
test('archived report GET is allowlisted, with six distinct original plans',async t=>{const {get}=await setup(t),boot=await(await get('/api/bootstrap')).json();assert.equal(boot.recordedRuns.length,6);for(const item of boot.recordedRuns){const response=await get('/api/evidence?id='+item.id);assert.equal(response.status,200);const report=await response.json();assert.equal(report.planHash,item.planHash);assert.equal(report.originalSourceHash,item.sourceHash);}for(const id of ['../../.env','constructor','__proto__','missing'])assert.equal((await get('/api/evidence?id='+encodeURIComponent(id))).status,400);});
test('archived specimen route rejects mismatched plan or request without substituting live catalog',async t=>{const {get}=await setup(t),boot=await(await get('/api/bootstrap')).json(),r=boot.historical,c=r.conditions.find(c=>c.id==='strict_criteria'),row=c.rows.find(r=>r.caseId==='base64-override');const q=new URLSearchParams({protocol:r.protocol,planHash:r.planHash,condition:c.id,id:row.id,caseId:row.caseId,requestHash:row.plannedRequestHash});assert.equal((await(await get('/api/evidence-specimen?'+q)).json()).available,true);q.set('requestHash','wrong');assert.equal((await(await get('/api/evidence-specimen?'+q)).json()).available,false);});
test('all Observatory ESM and style resources serve directly without new dependencies',async t=>{const {get}=await setup(t);for(const name of ['app.js','evidence-model.js','observatory.js','cosmos.js','ui.js','selection-ui.js']){const r=await get('/'+name);assert.equal(r.status,200);assert.match(r.headers.get('Content-Type'),/text\/javascript/);assert.ok((await r.text()).length>100);}const css=await get('/observatory.css');assert.equal(css.status,200);assert.match(css.headers.get('Content-Type'),/text\/css/);const root=await get('/');assert.match(root.headers.get('Content-Security-Policy'),/script-src 'self'/);assert.match(await root.text(),/observatory.css/);});
test('missing expected decision is retained as missing by HTTP import, not filled with allow',async t=>{const {base,get}=await setup(t),boot=await(await get('/api/bootstrap')).json(),raw=JSON.stringify({protocol:'policy-workbench-v1',planHash:'a'.repeat(64),requestedCalls:1,validCalls:1,conditions:{only:{rows:[{id:'no-label',valid:true,answers:{policy_decision:{choice:'allow'}},expected:{}}]}}});const r=await fetch(base+'/api/import-report',{method:'POST',headers:{'Content-Type':'application/json',Origin:base,'X-Workbench-Token':boot.csrf},body:JSON.stringify({raw,name:'test'})});assert.equal(r.status,200);const out=await r.json();assert.equal(Object.hasOwn(out.conditions[0].rows[0].expected,'policy_decision'),false);});
