import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {importReport,normalizeExpected,matchedComparison} from '../src/report.mjs';
import {loadEvidence,evidenceLibrary,evidenceSpecimen} from '../src/evidence-library.mjs';
import {defaultCondition,categoricalCounts,filterRows,rowIdentity,mapNodes,confusion,operationInfo,expectation} from '../public/evidence-model.js';
const latest=loadEvidence('consumer-admission-v1');
const counts=rows=>Object.fromEntries(Object.entries(categoricalCounts(rows,'policy_decision')));
for(const [id,expected] of [['inspection_question',{allow:64}],['inspection_criteria',{allow:64}],['strict_question',{allow:16,review:4,block:44}],['strict_criteria',{allow:16,review:4,block:44}],['contextual_question',{allow:26,review:6,block:32}],['contextual_criteria',{allow:26,review:6,block:32}],['rich_control',{allow:45,block:3}],['compact_both',{allow:45,block:3}]]){
 test('source-bound decision distribution: '+id,()=>assert.deepEqual(counts(latest.conditions.find(c=>c.id===id).rows),expected));
}
test('all 480 expected objects and model answers match original source row by row',()=>{const raw=JSON.parse(fs.readFileSync(new URL('../data/consumer-admission-v1.report.json',import.meta.url)));let n=0;for(const c of latest.conditions)for(let i=0;i<c.rows.length;i++){const x=raw.conditions[c.id].rows[i],r=c.rows[i];assert.deepEqual({...r.expected},x.expected);assert.deepEqual(r.answers,x.answers);assert.equal(r.plannedRequestHash,x.plannedRequestHash);n++;}assert.equal(n,480);});
test('preferred saved condition wins; new import starts with contextual admission not first control',()=>{assert.equal(defaultCondition(latest),'contextual_criteria');assert.equal(defaultCondition(latest,'inspection_question'),'inspection_question');assert.equal(defaultCondition(latest,'removed_condition'),'contextual_criteria');});
test('inspection scope is explicit and different from admission',()=>{assert.equal(operationInfo(latest.conditions.find(c=>c.id==='inspection_question')).allowLabel,'Allow inspection');assert.equal(operationInfo(latest.conditions.find(c=>c.id==='strict_question')).allowLabel,'Allow admission');assert.equal(operationInfo(latest.conditions[0]).kind,'historical');});
test('unknown expected value is ungraded, never an allow fallback',()=>{const rows=[{id:'x',expected:{},valid:true,answers:{policy_decision:{choice:'allow'}}}];assert.equal(expectation(rows[0],'policy_decision'),null);assert.deepEqual(counts(rows),{unavailable:1});assert.equal(filterRows(rows,{expectedDecision:'allow'}).length,0);assert.equal(filterRows(rows,{filter:'native'}).length,0);assert.equal(confusion(rows,'policy_decision').cells.find(c=>c.expected==='unavailable'&&c.observed==='allow').count,1);});
test('explicit protocol key aliases; conflicts rejected rather than silently choosing one',()=>{assert.deepEqual({...normalizeExpected({policyDecision:'block',inputContract:'violation'})},{policy_decision:'block',input_contract:'violation'});assert.throws(()=>normalizeExpected({policyDecision:'block',policy_decision:'allow'}),/Conflicting/);});
test('every confusion-matrix cell maps exactly to its filter results',()=>{for(const c of latest.conditions)for(const field of ['classification','policy_decision']){const m=confusion(c.rows,field);assert.equal(m.cells.reduce((n,c)=>n+c.count,0),c.rows.length);for(const cell of m.cells)assert.equal(filterRows(c.rows,{matrix:{field,expected:cell.expected,observed:cell.observed}}).length,cell.count);}});
test('galaxy observation nodes retain every row identity and classification status',()=>{for(const c of latest.conditions){const map=mapNodes(c.rows);assert.equal(map.nodes.length,c.rows.length);assert.equal(new Set(map.nodes.map(n=>n.key)).size,c.rows.length);assert.equal(map.nodes.filter(n=>n.status==='false_alarm').length,c.summary.attackDetection.falseAlarms);for(const n of map.nodes)assert.ok(Number.isFinite(n.x)&&Number.isFinite(n.y)&&Number.isFinite(n.z));}});
test('filter categories do not mutate or rewrite frozen labels',()=>{const before=JSON.stringify(latest);for(const c of latest.conditions)for(const filter of ['errors','false_alarms','misses','native','derived','contract'])filterRows(c.rows,{filter});assert.equal(JSON.stringify(latest),before);});
test('all six registered reports available, with distinct source and plan identities',()=>{const list=evidenceLibrary();assert.equal(list.length,6);assert.equal(new Set(list.map(r=>r.sourceHash)).size,6);assert.equal(new Set(list.map(r=>r.planHash)).size,6);});
test('historical compact import preserves camelCase expected decisions and separate baseline',()=>{const r=loadEvidence('compact-single-pass-48-v1');assert.equal(r.requestedCalls,48);assert.equal(r.observationRows,96);assert.equal(r.conditions[1].kind,'historical_reference');for(const c of r.conditions)assert.deepEqual(counts(c.rows),{allow:45,block:3});});
test('same fixture in two boundary repeats has two distinct inspectable row identities',()=>{const r=loadEvidence('boundary-fewshot-v2'),c=r.conditions.find(c=>c.id==='restored_open_set');assert.equal(c.rows.length,160);assert.equal(new Set(c.rows.map(rowIdentity)).size,160);const repeated=c.rows.filter(x=>x.id===c.rows[0].id);assert.equal(repeated.length,2);assert.notEqual(rowIdentity(repeated[0]),rowIdentity(repeated[1]));assert.equal(filterRows(c.rows,{repeat:'2'}).length,48);});
test('paired comparisons never silently bind repeat 2 to repeat 1',()=>{const row=(repeat,value)=>({id:'same',repeat,valid:true,expected:{classification:'benign'},answers:{classification:{choice:value}}});const r={conditions:[{id:'a',rows:[row(1,'attack'),row(2,'benign')]},{id:'b',rows:[row(1,'attack'),row(2,'benign')]}]};assert.equal(matchedComparison(r,'a','b').changes.length,0);});
test('deterministic feature classification is visible as code-derived, not invented native output',()=>{const r=loadEvidence('prompt-variant-lab-v1'),c=r.conditions.find(c=>c.id==='features_plain_code');assert.equal(c.rows.length,48);for(const row of c.rows){assert.equal(row.answers.classification.type,'code_derived');assert.equal(row.rawAnswers.classification,undefined);assert.ok(row.answerOrigins.classification.includes('not a native'));}});
test('historical raw expected values preserved even when display aliases normalize them',()=>{const r=loadEvidence('compact-single-pass-48-v1');for(const c of r.conditions)for(const row of c.rows){assert.equal(row.sourceExpected.policyDecision,row.expected.policy_decision);assert.equal(row.sourceExpected.inputContract,row.expected.input_contract);}});
test('historical report view round trips rows, origins and original source identity',()=>{for(const entry of evidenceLibrary()){const r=loadEvidence(entry.id),copy=importReport(JSON.stringify(r));assert.equal(copy.originalSourceHash,r.originalSourceHash);assert.deepEqual(JSON.parse(JSON.stringify(copy.conditions.map(c=>c.summary))),JSON.parse(JSON.stringify(r.conditions.map(c=>c.summary))));assert.deepEqual(copy.conditions.map(c=>c.rows.map(rowIdentity)),r.conditions.map(c=>c.rows.map(rowIdentity)));}});
test('archived specimen must match protocol, plan, condition, row ID and request hash',()=>{const c=latest.conditions.find(c=>c.id==='contextual_criteria'),row=c.rows.find(r=>r.caseId==='base64-override');const args={protocol:latest.protocol,planHash:latest.planHash,condition:c.id,id:row.id,caseId:row.caseId,requestHash:row.plannedRequestHash};assert.equal(evidenceSpecimen(args).available,true);for(const field of ['protocol','planHash','condition','id','caseId','requestHash'])assert.equal(evidenceSpecimen({...args,[field]:'wrong'}).available,false);});
test('predeclared disputed-case filter only removes specified acrostic fixture',()=>{const r=loadEvidence('boundary-fewshot-v2'),c=r.conditions[0];const filtered=filterRows(c.rows,{excludeDisputed:true});assert.equal(c.rows.length-filtered.length,6);assert.ok(filtered.some(r=>r.caseId==='rich-acrostic-message:benign'));});
test('release UI does not imply Observatory is a corporate byline',()=>{const text=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');assert.doesNotMatch(text,/by Observatory/);assert.match(text,/Jev policy workbench/);});
