import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {preset} from '../src/policy.mjs';import {makePlan} from '../src/planner.mjs';import {initAccount,openAccount,executePrepared} from '../src/runner.mjs';import {sha} from '../src/util.mjs';import {readLedgerEvents,immutableJson,unwrap} from '../vendor/admission-v1/io.mjs';
function fixture(t,{cap=1,options={}}={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'jwb-run-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));initAccount(root,cap);return {root,plan:makePlan(preset(),options)};}
function fake(plan,calls=[]){const expectations=new Map(plan.jobs.map(j=>[j.requestHash,j.expected]));return async request=>{calls.push(sha(JSON.stringify(request)));const e=expectations.get(sha(JSON.stringify(request)));return {response:{status:'ok',answers:Object.fromEntries(Object.entries(request.questions).map(([id,q])=>{const selected=e[id]??Object.keys(q.criteria)[0];return [id,{type:'choice',choice:selected,confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===selected?1:0]))}];})),usage:{inputTokens:100,outputTokens:20},latencyMs:1},reportedProviderModel:'jev-1.13.0'};};}
const execute=(plan,acct,opts)=>acct.api.withLock(acct.lock,()=>executePrepared(plan,acct,{intervalMs:0,...opts}));
test('complete simulated Gold run exercises all 120 calls and multiple ledger stages',async t=>{const {root,plan}=fixture(t,{options:{tier:'gold'}}),acct=await openAccount({account:root}),calls=[];const result=await execute(plan,acct,{infer:fake(plan,calls)});assert.equal(result.report.status,'complete');assert.equal(calls.length,120);assert.equal(result.report.validCalls,120);assert.equal(result.report.budget.bundleHeldUsd,0);assert.equal(result.report.budget.bundleKnownUsageUsd,120*100*42/1e9);assert.equal(readLedgerEvents(acct.ledgerDir).length,240);assert.equal(Object.keys(result.report.conditions).length,2);assert.ok(fs.existsSync(path.join(path.dirname(result.path),'source/src/compiler.mjs')));});
test('invocation limit and resume do not repeat paid job identities',async t=>{const {root,plan}=fixture(t),acct=await openAccount({account:root}),calls=[],infer=fake(plan,calls);let first=await execute(plan,acct,{infer,limit:3});assert.equal(first.dispatchedNow,3);assert.equal(first.report.status,'partial');let second=await execute(plan,acct,{infer});assert.equal(second.dispatchedNow,plan.jobs.length-3);assert.equal(second.report.status,'complete');let third=await execute(plan,acct,{infer});assert.equal(third.dispatchedNow,0);assert.equal(calls.length,plan.jobs.length);});
test('transport failure remains held and cannot auto-retry',async t=>{const {root,plan}=fixture(t),acct=await openAccount({account:root});let n=0;const infer=async()=>{n++;throw Error('fake network fault');};const result=await execute(plan,acct,{infer});assert.equal(n,1);assert.equal(result.report.status,'stopped');assert.ok(result.report.budget.bundleHeldUsd>0);await assert.rejects(execute(plan,acct,{infer}),/halted/);assert.equal(n,1);});
test('valid response with missing usage stops and reserves uncertain charge',async t=>{const {root,plan}=fixture(t),acct=await openAccount({account:root});const f=fake(plan);const result=await execute(plan,acct,{infer:async req=>{let e=await f(req);e.response.usage=null;return e;}});assert.equal(result.report.stopReason,'missing_usage');assert.equal(result.dispatchedNow,1);assert.ok(result.report.budget.bundleHeldUsd>0);});
test('model-version change records charge and halts',async t=>{const {root,plan}=fixture(t),acct=await openAccount({account:root}),f=fake(plan);const result=await execute(plan,acct,{infer:async req=>({...await f(req),reportedProviderModel:'jev-changed'})});assert.equal(result.report.stopReason,'model_version_changed');assert.equal(result.dispatchedNow,1);assert.equal(result.report.validCalls,0);assert.ok(result.report.budget.bundleKnownUsageUsd>0);});
test('reservation without saved response is never redispatched',async t=>{const {root,plan}=fixture(t),acct=await openAccount({account:root}),j=plan.jobs[0];const stageId='rich-'+sha(plan.manifest.planHash+':0').slice(0,24);immutableJson(path.join(acct.ledgerDir,'0000000001.json'),{sequence:1,type:'reserve',key:stageId+':'+j.id,stageId,requestHash:j.requestHash,reservationNanoUsd:j.reservationInputTokens*42});let n=0;await assert.rejects(execute(plan,acct,{infer:async()=>{n++;}}),/Uncertain dispatch/);assert.equal(n,0);});
test('operator stop happens before any new reservation',async t=>{const {root,plan}=fixture(t),acct=await openAccount({account:root});const r=await execute(plan,acct,{infer:fake(plan),shouldStop:()=>true});assert.equal(r.dispatchedNow,0);assert.equal(r.report.stopReason,'operator_stop');assert.equal(readLedgerEvents(acct.ledgerDir).length,0);});
test('insufficient account cap blocks inference',async t=>{const {root,plan}=fixture(t,{cap:.001}),acct=await openAccount({account:root});let n=0;await assert.rejects(execute(plan,acct,{infer:async()=>n++}),/Shared budget cannot cover/);assert.equal(n,0);});
test('standalone cap is explicit and cannot be reset by reinitialization',t=>{const {root}=fixture(t);assert.throws(()=>initAccount(root,3),/cannot be reset/);assert.equal(JSON.parse(fs.readFileSync(path.join(root,'account.json'))).maximumNanoUsd,1e9);});
test('prior-history floor prevents misusing a missing project ledger',async t=>{const {root,plan}=fixture(t),acct=await openAccount({account:root});acct.minimumPriorNano=1_450_070_202;let n=0;await assert.rejects(execute(plan,acct,{infer:async()=>n++}),/history is missing/);assert.equal(n,0);});
test('settled evidence modification prevents replay',async t=>{const {root,plan}=fixture(t),acct=await openAccount({account:root});const r=await execute(plan,acct,{infer:fake(plan),limit:1});const file=path.join(path.dirname(r.path),'records',sha(plan.jobs[0].id)+'.json');fs.appendFileSync(file,' ');await assert.rejects(execute(plan,acct,{infer:fake(plan)}),/Raw evidence changed/);});
