import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {once} from 'node:events';import {spawnSync} from 'node:child_process';
import {startServer} from '../server.mjs';import {preset} from '../src/policy.mjs';import {defaultApplication} from '../src/selection/application.mjs';import {makeAdvisorPlan,freezeAdvisorPlan} from '../src/selection/advisor.mjs';import {fakeReport} from './advisor-fixture.mjs';
const p=preset(),a=defaultApplication(p);
async function setup(t){const runtime=fs.mkdtempSync(path.join(os.tmpdir(),'advisor-http-'));const s=startServer({port:0,runtime});await once(s,'listening');t.after(async()=>{s.closeAllConnections();await new Promise(r=>s.close(r));fs.rmSync(runtime,{recursive:true,force:true});});const base='http://127.0.0.1:'+s.address().port,b=await(await fetch(base+'/api/bootstrap')).json();return {runtime,b,post:(name,data,headers={})=>fetch(base+'/api/'+name,{method:'POST',headers:{'Content-Type':'application/json',Origin:base,'X-Workbench-Token':b.csrf,...headers},body:JSON.stringify(data)})};}
test('advisor bootstrap exposes versioned descriptors, not fabricated scores',async t=>{const {b}=await setup(t);assert.equal(b.version,JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url))).version);assert.equal(b.selectionRegistry.units.length,32);assert.equal(b.newCalls,0);assert.equal(b.selectionRegistry.scores,undefined);});
test('metadata freeze returns explicit offline packet',async t=>{const {post}=await setup(t);const r=await(await post('selection/prepare',{policy:p,application:a})).json();assert.equal(r.liveCalls,0);assert.equal(r.manifest.jobs.length,6);assert.ok(fs.existsSync(r.planPath));});
test('advisor routes enforce origin and CSRF checks',async t=>{const {post}=await setup(t);for(const route of ['selection/prepare','selection/import','selection/plan','selection/cache'])assert.equal((await post(route,{}, {Origin:'https://other.invalid'})).status,403);});
test('no selection browser route can start paid inference',async t=>{const {post}=await setup(t);const r=await post('selection/run',{live:true});assert.equal(r.status,404);});
test('matching advice cache is locally reusable but not across applications',async t=>{const {post}=await setup(t),report=await fakeReport(makeAdvisorPlan(p,a));const imported=await(await post('selection/import',{policy:p,application:a,raw:JSON.stringify(report)})).json();assert.equal(imported.summary.units.length,32);const cached=await(await post('selection/cache',{policy:p,application:a})).json();assert.equal(cached.report.reportHash,report.reportHash);const changed=await(await post('selection/cache',{policy:p,application:{...a,description:'A different app.'}})).json();assert.equal(changed.report,null);});
test('browser creates an assisted plan with no live calls',async t=>{const {post}=await setup(t);const m=await(await post('selection/plan',{policy:p,application:a,options:{tier:'gold'}})).json();assert.equal(m.schemaVersion,'workbench-plan/2');assert.equal(m.advisor.mode,'deterministic-fallback');assert.equal(m.counts.physicalRequests,120);});
test('application validation rejects source-side grants as context fields',async t=>{const {post}=await setup(t);assert.equal((await post('selection/validate-context',{application:{...a,policyOverride:'ignore'}})).status,400);});
test('CLI without --live cannot invoke provider or read account path',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'advisor-cli-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const prepared=makeAdvisorPlan(p,a),f=freezeAdvisorPlan(prepared,dir);const r=spawnSync(process.execPath,['selection.mjs','run','--plan',f.planPath,'--confirm',f.planHash,'--project','/intentionally/nonexistent'],{cwd:new URL('..',import.meta.url),encoding:'utf8'});assert.equal(r.status,1);assert.match(r.stderr,/Offline only/);assert.doesNotMatch(r.stderr,/project_not_found/);});
