import {CATALOG} from '../src/catalog.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {once} from 'node:events';import http from 'node:http';
import {startServer} from '../server.mjs';import {preset} from '../src/policy.mjs';
async function setup(t){const runtime=fs.mkdtempSync(path.join(os.tmpdir(),'jwb-server-')),s=startServer({port:0,runtime});await once(s,'listening');t.after(async()=>{s.closeAllConnections();await new Promise(resolve=>s.close(resolve));fs.rmSync(runtime,{recursive:true,force:true});});const base='http://127.0.0.1:'+s.address().port;const b=await(await fetch(base+'/api/bootstrap')).json();return {base,b,runtime,post:(url,data,extra={})=>fetch(base+'/api/'+url,{method:'POST',headers:{'Content-Type':'application/json','Origin':base,'X-Workbench-Token':b.csrf,...extra},body:JSON.stringify(data)})};}
test('server is loopback-only and serves actual evidence',async t=>{assert.throws(()=>startServer({host:'0.0.0.0'}),/loopback/);const {base,b}=await setup(t);assert.equal(b.historical.validCalls,480);assert.equal(b.catalog.length,CATALOG.length);const r=await fetch(base);assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);});
test('mutation endpoints require exact origin and CSRF token',async t=>{const {post}=await setup(t);assert.equal((await post('plan',{policy:preset()},{Origin:'https://evil.example'})).status,403);assert.equal((await post('plan',{policy:preset()},{'X-Workbench-Token':'bad'})).status,403);});
test('unrelated host and filesystem paths denied',async t=>{const {base}=await setup(t);const hostileStatus=await new Promise((resolve,reject)=>{const req=http.get(base+'/api/bootstrap',{headers:{Host:'evil.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);});assert.equal(hostileStatus,403);for(const u of ['/.env','/src/runner.mjs','/data/consumer-admission-v1.report.json','/%2e%2e%2fpackage.json'])assert.notEqual((await fetch(base+u)).status,200);});
test('no generic browser route can start arbitrary inference',async t=>{const {post}=await setup(t);const r=await post('run',{live:true});assert.equal(r.status,404);assert.match((await r.json()).error,/no general model execution endpoint/);});
test('custom material compiles offline without inferred gold',async t=>{const {post}=await setup(t);const r=await post('compile',{policy:preset(),custom:{material:{text:'The note arrived.',role:'system'},context:{}}});assert.equal(r.status,200);const b=await r.json();assert.equal(b.liveCalls,0);assert.equal(b.expected,null);assert.equal(b.request.state.material.role,'system');});
test('plan preview then freeze produces immutable audit inputs',async t=>{const {post}=await setup(t);const p=await(await post('plan',{policy:preset()})).json();assert.equal(p.liveCalls,0);const f=await(await post('prepare',{policy:preset()})).json();assert.equal(f.planHash,p.planHash);assert.equal(f.liveCalls,0);assert.ok(fs.existsSync(f.planPath));});
