import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {once} from 'node:events';
import {preset,validatePolicy} from '../src/policy.mjs';
import {defaultApplication,applicationKey} from '../src/selection/application.mjs';
import {SETUP_FIELDS,setupRequest,applySetupSummary,undoSetupTransaction} from '../src/setup.mjs';
import {makeAdvisorPlan,freezeAdvisorPlan,adviceSummary,validateAdviceReport} from '../src/selection/advisor.mjs';
import {createLocalConnection} from '../src/local-connection.mjs';
import {startServer} from '../server.mjs';
import {sha} from '../src/util.mjs';
import {workflowStatus,appStamp,draftStamp,estimatedBudgetView} from '../public/workflow-model.js';
import {setupLanguageReview} from '../public/workflow-model.js';
import {policySnapshot} from '../public/guided.js';
import {compileCase} from '../src/compiler.mjs';
import {CATALOG,expectedFor} from '../src/catalog.mjs';
import {SETUP_LANGUAGE_LISTS,SETUP_VERSION} from '../src/setup.mjs';
const KEY='SYNTHETIC_ONLY_SETUP_TEST_KEY_050';
const policy=()=>preset('strict');
const app=p=>({...defaultApplication(p),name:'Billing support',description:'Read billing conversations and structured records in English and Spanish. Admit relevant task data. Refund actions and account disclosures exist and must be covered.'});
const choices={task:'billing-support',mode:'contextual',language_scope:'controlling_instructions',languages:'english_spanish',surface_conversation_history:'present',surface_tool_results:'present',capability_external_actions:'present',capability_sensitive_disclosure:'present'};
export function setupInference({select=choices,model='jev-1.13.0',missingUsage=false}={}){return async request=>({reportedProviderModel:model,response:{status:'ok',latencyMs:2,usage:missingUsage?null:{inputTokens:150,outputTokens:32},answers:Object.fromEntries(Object.entries(request.questions).map(([id,q])=>{const opts=Object.keys(q.criteria),choice=select[id]??(opts.includes('not_indicated')?'not_indicated':opts.includes('keep_current')?'keep_current':opts[0]);return [id,{type:'choice',choice,confidence:1,probabilities:Object.fromEntries(opts.map(k=>[k,k===choice?1:0]))}];}))}});}
async function simulatedReport(p=policy(),a=app(p),select=choices){const prepared=makeAdvisorPlan(p,a,{mode:'setup',maxUsd:.01,maxInputTokens:null}),j=prepared.jobs[0],e={...await setupInference({select})(j.request),key:'synthetic-only',jobId:j.id,requestHash:j.requestHash,receivedAt:'2026-09-19T00:00:00Z'};const report={protocol:'catalog-advisor-report/1',mode:'setup',manifest:prepared.manifest,status:'complete',stopReason:null,rows:[{jobId:j.id,requestHash:j.requestHash,rawHash:sha(JSON.stringify(e)+'\n'),evidence:e,evidenceHash:sha(e),valid:true,error:null}],failures:[],budget:{knownNanoUsd:150*42,heldNanoUsd:0,inputTokens:150,heldInputTokens:0,maximumUsd:.01},dispatched:1};return {...report,reportHash:sha(report)};}
function env(t,opts={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wb05-setup-')),runtime=path.join(dir,'runtime'),account=path.join(dir,'account');let calls=0;const connection=createLocalConnection({runtime,now:opts.now??Date.now,inferFactory:async({key})=>{assert.equal(key,KEY);return async q=>{calls++;return (opts.infer??setupInference())(q);};}});t.after(()=>{connection.close();fs.rmSync(dir,{recursive:true,force:true});});return {dir,runtime,account,connection,calls:()=>calls,connect:()=>connection.connect({source:'paste',apiKey:KEY,accountKind:'standalone',directory:account,createAccount:true,accountLimitUsd:1}),prepare:()=>{const p=policy(),plan=makeAdvisorPlan(p,app(p),{mode:'setup',maxUsd:.01,maxInputTokens:null});freezeAdvisorPlan(plan,path.join(runtime,'advisor-plans',plan.manifest.planHash));return plan;}};}
async function finished(c,id){for(let i=0;i<100;i++){const r=c.runStatus(id);if(r.status!=='running')return r;await new Promise(r=>setTimeout(r,20));}throw Error('Timed out waiting for simulated setup request');}
function scan(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?scan(path.join(dir,e.name)):[path.join(dir,e.name)]);}

test('setup is one native request with sixteen independent bounded choices',()=>{const p=policy(),j=setupRequest(p,app(p));assert.equal(j.mapping.length,16);assert.equal(Object.keys(j.request.questions).length,16);assert.equal(j.request.model,p.model);assert.ok(j.wireBytes<50000);assert.ok(Object.values(j.request.questions).every(q=>q.type==='choice'));});
test('setup state excludes test gold, catalog material, paths, budgets and credentials',()=>{const p=policy(),j=setupRequest(p,app(p));assert.deepEqual(Object.keys(j.request.state),['application','currentDraft','optionLibraryVersion','targetLanguageCapabilities','notice']);assert.ok(!j.body.includes('maxUsd'));assert.ok(!j.body.includes('TYPESAFE_API_KEY'));assert.ok(!j.body.includes('expectedByPolicy'));});
test('an imported descriptor catalog cannot become setup generation',()=>{const p=policy();assert.throws(()=>makeAdvisorPlan(p,app(p),{mode:'setup'},[]),/Imported descriptors/);});
test('setup summary is separately typed and starts entirely unchecked',async()=>{const p=policy(),r=await simulatedReport(p),s=adviceSummary(r,{mode:'setup',policy:p,application:app(p)});assert.equal(s.schemaVersion,SETUP_VERSION);assert.ok(s.suggestions.length>=6);assert.ok(s.suggestions.every(x=>x.selected===false));assert.equal(s.knownUsageUsd,150*42/1e9);assert.equal(s.units,undefined);});
test('apply only the selected field; unrelated policy values remain unchanged',async()=>{const p=policy(),a=app(p),s=adviceSummary(await simulatedReport(p,a)),tx=applySetupSummary(p,a,s,['languages']);assert.deepEqual(tx.after.policy.languages.allowed,['en','es']);assert.equal(tx.after.policy.mode,'strict');assert.deepEqual(tx.after.policy.task,p.task);assert.deepEqual(tx.after.application,a);});
test('mode suggestions may clear exception grants, but never enable them',async()=>{const p=preset('contextual'),a=app(p),s=adviceSummary(await simulatedReport(p,a,{mode:'strict'})),tx=applySetupSummary(p,a,s,['mode']);assert.equal(tx.after.policy.mode,'strict');assert.deepEqual(tx.after.policy.representations.enabledExceptions,[]);const s2=adviceSummary(await simulatedReport(policy(),app(policy()))),tx2=applySetupSummary(policy(),app(policy()),s2,['mode']);assert.equal(tx2.after.policy.mode,'contextual');assert.deepEqual(tx2.after.policy.representations.enabledExceptions,[]);});
test('multiple input and capability changes merge without dropping another selection',async()=>{const p=policy(),a=app(p),s=adviceSummary(await simulatedReport(p,a)),tx=applySetupSummary(p,a,s,['surface_tool_results','surface_conversation_history','capability_external_actions','capability_sensitive_disclosure']);assert.ok(tx.after.application.surfaces.includes('tool_results'));assert.ok(tx.after.application.surfaces.includes('conversation_history'));assert.ok(tx.after.application.capabilities.includes('external_actions'));assert.ok(tx.after.application.capabilities.includes('sensitive_disclosure'));assert.equal(tx.after.policy.mode,'strict');});
test('unknown, duplicate and empty selections fail without a partial edit',async()=>{const p=policy(),a=app(p),before=sha({p,a}),s=adviceSummary(await simulatedReport(p,a));for(const ids of [[],['budget'],['languages','languages'],['__proto__']])assert.throws(()=>applySetupSummary(p,a,s,ids));assert.equal(sha({p,a}),before);});
test('stale policy and stale application both reject setup edits',async()=>{const p=policy(),a=app(p),s=adviceSummary(await simulatedReport(p,a));assert.throws(()=>applySetupSummary({...p,name:'new'},a,s,['languages']),/stale/);assert.throws(()=>applySetupSummary(p,{...a,description:'New description'},s,['languages']),/stale/);});
test('undo restores exact pre-apply draft and refuses to overwrite a later edit',async()=>{const p=policy(),a=app(p),s=adviceSummary(await simulatedReport(p,a)),tx=applySetupSummary(p,a,s,['languages','task']);assert.deepEqual(undoSetupTransaction(tx.after.policy,tx.after.application,tx),{policy:p,application:a});assert.throws(()=>undoSetupTransaction({...tx.after.policy,name:'new edit'},tx.after.application,tx),/newer edits/);});
test('unsupported app/language combinations remain manual, not invented recommendations',async()=>{const p=policy(),r=await simulatedReport(p,app(p),{task:'other_or_custom',languages:'manual_review'}),s=adviceSummary(r);assert.ok(s.notes.some(n=>n.field==='task'));assert.ok(s.notes.some(n=>n.field==='languages'));assert.ok(!s.suggestions.some(n=>n.id==='task'||n.id==='languages'));});
test('Spanish-only advice replaces English and reaches the snapshot, compiler and test expectations',async()=>{
 const p=policy(),a={...app(p),description:'Review incident records. Admit Spanish only; reject English input.'};
 const report=await simulatedReport(p,a,{languages:'spanish'}),summary=adviceSummary(report);
 assert.equal(report.manifest.catalogSource,SETUP_VERSION);
 const before={policy:p,application:a,setupSummary:summary,setupInputStamp:draftStamp(p,a)};
 assert.equal(setupLanguageReview(before),'pending');
 assert.match(policySnapshot(before),/Language suggestions have not been applied/);
 assert.deepEqual(p.languages.allowed,['en'],'No automatic mutation before review');
 const tx=applySetupSummary(p,a,summary,['languages']),next=tx.after.policy;
 assert.deepEqual(next.languages,{mode:'allowlist',allowed:['es'],scope:'natural_language_content'});
 const spanish=CATALOG.find(c=>c.id==='language-es-benign'),english=CATALOG.find(c=>c.id==='ordinary-note');
 assert.deepEqual(compileCase(next,spanish).request.state.policy.languageContract,next.languages);
 assert.equal(expectedFor(next,spanish).policy_decision,'allow');
 assert.equal(expectedFor(next,english).language_contract,'violation');
 assert.equal(expectedFor(next,english).policy_decision,'block');
 assert.equal(expectedFor(next,CATALOG.find(c=>c.id==='language-es-attack')).policy_decision,'block');
 const after={...tx.after,setupTransaction:tx};
 assert.equal(setupLanguageReview(after),null);
 assert.match(policySnapshot(after),/<h3>Spanish<\/h3>/);
 assert.doesNotMatch(policySnapshot(after),/<h3>English<\/h3>/);
});
test('every fixed language choice applies its exact list without retaining English',async()=>{
 for(const [choice,allowed] of Object.entries(SETUP_LANGUAGE_LISTS)){
  const p=policy();p.languages={...p.languages,mode:'any',allowed:[]};const a=app(p);
  const summary=adviceSummary(await simulatedReport(p,a,{languages:choice}));
  const result=applySetupSummary(p,a,summary,['languages']).after.policy;
  assert.deepEqual(result.languages.allowed,allowed,choice);assert.equal(result.languages.mode,'allowlist');
 }
 const p=policy(),a=app(p),summary=adviceSummary(await simulatedReport(p,a,{languages:'any_language'}));
 assert.deepEqual(applySetupSummary(p,a,summary,['languages']).after.policy.languages,{mode:'any',allowed:[],scope:'natural_language_content'});
});
test('unresolved language requirements remain visible after applying unrelated suggestions',async()=>{
 const p=policy(),a=app(p),summary=adviceSummary(await simulatedReport(p,a,{task:'billing-support',languages:'manual_review'}));
 const before={policy:p,application:a,setupSummary:summary,setupInputStamp:draftStamp(p,a)};
 assert.equal(setupLanguageReview(before),'manual');assert.match(policySnapshot(before),/Edit language rule/);
 const tx=applySetupSummary(p,a,summary,['task']),after={...tx.after,setupTransaction:tx};
 assert.equal(setupLanguageReview(after),'manual');assert.match(policySnapshot(after),/still permits English/);
});
test('forged budget path and enabled grants are rejected as defense in depth',async()=>{const p=policy(),a=app(p),s=adviceSummary(await simulatedReport(p,a));const evil={...s,suggestions:[{id:'evil',changes:[{target:'policy',path:['budget'],after:100}]}]};assert.throws(()=>applySetupSummary(p,a,evil,['evil']),/Unsupported/);evil.suggestions[0].changes=[{target:'policy',path:['representations','enabledExceptions'],after:['format-analysis']}];assert.throws(()=>applySetupSummary(p,a,evil,['evil']),/cannot enable/);});
test('a setup report cannot masquerade as ranking advice',async()=>{const r=await simulatedReport();assert.throws(()=>validateAdviceReport(r,{mode:'rank'}),/purpose/);});
test('setup report tampering and missing usage are rejected',async()=>{const r=await simulatedReport();const changed=structuredClone(r);changed.rows[0].evidence.response.answers.mode.choice='inspection';assert.throws(()=>adviceSummary(changed),/hash/);const missing=structuredClone(r);missing.rows[0].evidence.response.usage=null;assert.throws(()=>adviceSummary(missing));});
test('loading a key and preparing/authorizing setup makes zero calls',async t=>{const x=env(t);await x.connect();const p=x.prepare(),auth=await x.connection.authorize({planHash:p.manifest.planHash});assert.equal(auth.mode,'setup');assert.match(auth.dataDisclosure,/application description/);assert.equal(auth.requests,1);assert.equal(x.calls(),0);});
test('one approved simulated setup request settles once and stores no secret',async t=>{const x=env(t);await x.connect();const p=x.prepare(),q=await x.connection.authorize({planHash:p.manifest.planHash}),run=await x.connection.run({token:q.token,planHash:q.planHash,confirmPaid:true}),done=await finished(x.connection,run.id);assert.equal(done.status,'complete',done.error);assert.equal(x.calls(),1);assert.equal(done.report.mode,'setup');assert.equal(adviceSummary(done.report).suggestions[0].selected,false);assert.equal((await x.connection.status()).account.knownUsageUsd,150*42/1e9);for(const f of scan(x.dir))assert.ok(!fs.readFileSync(f,'utf8').includes(KEY),f);assert.ok(fs.existsSync(path.join(x.runtime,'setup-advice',done.report.reportHash+'.json')));});
test('setup confirmation cannot be replayed or survive key rotation',async t=>{const x=env(t);await x.connect();const p=x.prepare(),q=await x.connection.authorize({planHash:p.manifest.planHash});await x.connect();await assert.rejects(()=>x.connection.run({token:q.token,planHash:q.planHash,confirmPaid:true}));assert.equal(x.calls(),0);});
test('setup confirmation expires without sending a call',async t=>{let now=100;const x=env(t,{now:()=>now});await x.connect();const p=x.prepare(),q=await x.connection.authorize({planHash:p.manifest.planHash});now=q.expiresAt+1;await assert.rejects(()=>x.connection.run({token:q.token,planHash:q.planHash,confirmPaid:true}));assert.equal(x.calls(),0);});
test('setup request failure preserves uncertain accounting, never retries',async t=>{const x=env(t,{infer:async()=>{throw Error('failed '+KEY);}});await x.connect();const p=x.prepare(),q=await x.connection.authorize({planHash:p.manifest.planHash}),run=await x.connection.run({token:q.token,planHash:q.planHash,confirmPaid:true}),done=await finished(x.connection,run.id);assert.equal(done.status,'stopped');assert.equal(x.calls(),1);assert.ok((await x.connection.status()).account.heldUsd>0);assert.ok(!JSON.stringify(done).includes(KEY));});
test('setup changed provider model is not accepted or applied',async t=>{const x=env(t,{infer:setupInference({model:'different'})});await x.connect();const p=x.prepare(),q=await x.connection.authorize({planHash:p.manifest.planHash}),run=await x.connection.run({token:q.token,planHash:q.planHash,confirmPaid:true}),done=await finished(x.connection,run.id);assert.equal(done.status,'stopped');assert.equal(x.calls(),1);assert.throws(()=>adviceSummary(done.report));});
test('missing setup usage prevents advice from guiding a draft',async t=>{const x=env(t,{infer:setupInference({missingUsage:true})});await x.connect();const p=x.prepare(),q=await x.connection.authorize({planHash:p.manifest.planHash}),run=await x.connection.run({token:q.token,planHash:q.planHash,confirmPaid:true}),done=await finished(x.connection,run.id);assert.equal(done.status,'stopped');assert.ok((await x.connection.status()).account.heldUsd>0);});
test('recorded historical evidence is not completion of a new draft workflow',()=>{const p=policy(),a=app(p),s={policy:p,application:a,journey:{description:appStamp(a),rules:draftStamp(p,a)},evidence:{planHash:'old',status:'complete',validCalls:480,requestedCalls:480},frozen:{planHash:'new',manifest:{state:'prepared_offline'}}};assert.equal(workflowStatus(s).setupCount,3);assert.equal(workflowStatus(s).run,false);assert.equal(workflowStatus(s).complete,false);});
test('draft edits invalidate reviewed rules; copying a command cannot complete a run',()=>{const p=policy(),a=app(p),j={description:appStamp(a),rules:draftStamp(p,a)},s={policy:{...p,name:'edit'},application:a,journey:j};assert.equal(workflowStatus(s).done.rules,false);assert.equal(workflowStatus(s).run,false);});
test('only matching complete recorded plan marks a workflow complete',()=>{const p=policy(),a=app(p),s={policy:p,application:a,journey:{description:appStamp(a),rules:draftStamp(p,a)},frozen:{planHash:'new',manifest:{state:'prepared_offline'}},evidence:{planHash:'new',status:'complete',validCalls:12,requestedCalls:12,dispatched:12}};assert.equal(workflowStatus(s).complete,true);s.evidence.status='partial';assert.equal(workflowStatus(s).complete,false);});
test('large entered budget displays headroom and never invents observations',()=>{const b=estimatedBudgetView({requestedUsd:50,selectedReservationUsd:.1,estimatedUsd:.04,completeCatalogInBudget:true});assert.equal(b.unused,49.9);assert.equal(b.complete,true);});
test('setup HTTP routes use exact origin and CSRF, never open an arbitrary execution endpoint',async t=>{const runtime=fs.mkdtempSync(path.join(os.tmpdir(),'setup-http-')),s=startServer({port:0,runtime});await once(s,'listening');t.after(async()=>{s.closeAllConnections();await new Promise(r=>s.close(r));fs.rmSync(runtime,{recursive:true,force:true});});const base='http://127.0.0.1:'+s.address().port,boot=await(await fetch(base+'/api/bootstrap')).json(),post=(route,data,origin=base)=>fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,'X-Workbench-Token':boot.csrf},body:JSON.stringify(data)}),p=policy(),a=app(p);
 for(const route of ['setup/prepare','setup/request','setup/import','setup/apply','setup/undo'])assert.equal((await post(route,{},'https://other.invalid')).status,403);
 const saved=await(await post('setup/prepare',{policy:p,application:a})).json();assert.equal(saved.liveCalls,0);assert.equal(saved.manifest.jobs.length,1);const req=await(await post('setup/request',{planHash:saved.planHash})).json();assert.equal(Object.keys(req.request.questions).length,16);assert.equal((await post('setup/request',{planHash:'../../.env'})).status,400);assert.equal((await post('setup/run',{live:true})).status,404);
 const report=await simulatedReport(p,a);assert.equal((await post('selection/import',{raw:JSON.stringify(report),policy:p,application:a})).status,400);const imported=await(await post('setup/import',{raw:JSON.stringify(report),policy:p,application:a})).json();assert.ok(imported.summary.suggestions.length);assert.equal((await post('setup/apply',{raw:JSON.stringify(report),policy:p,application:a,selected:['maxUsd']})).status,400);
 const tx=await(await post('setup/apply',{raw:JSON.stringify(report),policy:p,application:a,selected:['languages']})).json();assert.deepEqual(tx.after.policy.languages.allowed,['en','es']);
});
